version: '3'

services:
  mssql-server:
    image:  mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - mssql-server-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlPassword123!
    ports:
      - "5000:1433"

volumes:
  mssql-server-data: